name: 'Generate documentation with Doxygen'

on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:

env:
  TARGETS: f7
  DEFAULT_TARGET: f7
  FBT_TOOLCHAIN_PATH: /runner/_work

jobs:
  doxygen:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Decontaminate previous build leftovers'
        run: |
          if [ -d .git ]; then
            git submodule status || git checkout "$(git rev-list --max-parents=0 HEAD | tail -n 1)"
          fi

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true

      - name: 'Get commit details'
        id: names
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"

      - name: 'Generate documentation'
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'documentation/'
          doxyfile-path: './Doxyfile-awesome.cfg'

      - name: 'Upload dev documentation'
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        uses: prewk/s3-cp-action@v2
        with:
          aws_s3_endpoint: "${{ secrets.FW_DOCS_AWS_ENDPOINT }}"
          aws_access_key_id: "${{ secrets.FW_DOCS_AWS_ACCESS_KEY }}"
          aws_secret_access_key: "${{ secrets.FW_DOCS_AWS_SECRET_KEY }}"
          source: "./documentation/build/html"
          dest: "s3://${{ secrets.FW_DOCS_AWS_BUCKET }}/dev"
          flags: "--recursive --acl public-read"

      - name: 'Upload tag documentation to Github Pages'
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build/html
          publish_branch: 'doc-${{steps.names.outputs.branch_name}}'

